### ISSUE TITLE
libudev problems

### ISSUE THREAD

**Issue by patrickelectric** [berkowski/mio-serial#18]
It fails to compile with: `/usr/lib/libudev.so: file not recognized: File format not recognized`
`cargo build --target=armv7-unknown-linux-gnueabihf` Any idea of how to solve that ?

My cargo file
```toml
[dependencies]
clap = "2.31.2"
libc = "0.2.*"
mio = "0.6"
mio-serial = "3.*"
serialport = "3.*"
```
